DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE LOAN CASCADE CONSTRAINTS;
DROP TABLE TAX CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE HELPDESK CASCADE CONSTRAINTS;

CREATE TABLE COMPANY 
(
  COMPANYID VARCHAR2(100) NOT NULL, 
  COMPANYNAME VARCHAR2(100) NOT NULL, 
  ADDRESS VARCHAR2(100) NOT NULL,
  PRIMARY KEY (COMPANYID) ENABLE 
);

CREATE TABLE DEPARTMENT 
(
  DEPARTMENTID VARCHAR2(100) NOT NULL,
  DEPARTMENTNAME VARCHAR2(100) NOT NULL,
  COMPANYID VARCHAR2(100) NOT NULL,
  PRIMARY KEY (DEPARTMENTID )ENABLE,
  FOREIGN KEY(COMPANYID) REFERENCES COMPANY(COMPANYID) ENABLE
);

CREATE TABLE TAX 
(
  TAXID VARCHAR2(100) NOT NULL,
  TAXVALUE NUMBER(38, 0) NOT NULL,
  DOCUMENT VARCHAR2(100) NOT NULL,
  EMPLOYEEID VARCHAR2(100) NOT NULL,
  PRIMARY KEY (TAXID) ENABLE
);

CREATE TABLE HELPDESK 
(
  HELPDESKID VARCHAR2(100) NOT NULL,
  HELPDESKNAME VARCHAR2(100) NOT NULL,
  EMPLOYEEID VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(100) NOT NULL,
  PRIMARY KEY (HELPDESKID) ENABLE
);

CREATE TABLE EMPLOYEE 
(
  EMPLOYEEID VARCHAR2(100) NOT NULL, 
  FIRSTNAME VARCHAR2(100) NOT NULL,
  LASTNAME VARCHAR2(100) NOT NULL,
  USERNAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(100) NOT NULL,
  CITY VARCHAR2(100) NOT NULL,
  STATE VARCHAR2(100) NOT NULL,
  ZIP VARCHAR2(100) NOT NULL,
  PHONENUMBER VARCHAR2(100) NOT NULL,
  DEPARTMENTID VARCHAR2(100),
  TAXID VARCHAR2(100),
  COMPANYID VARCHAR2(100) NOT NULL,
  PRIMARY KEY (EMPLOYEEID) ENABLE,
  FOREIGN KEY(TAXID) REFERENCES TAX(TAXID) ENABLE,
  FOREIGN KEY(COMPANYID) REFERENCES COMPANY(COMPANYID) ENABLE
);

CREATE TABLE LOAN 
(
  LOANID VARCHAR2(100) NOT NULL,
  COMPANYID VARCHAR2(100) NOT NULL,
  EMPLOYEEID VARCHAR2(100) NOT NULL,
  VALUE NUMBER(38, 0) NOT NULL,
  PRIMARY KEY (LOANID) ENABLE,
  FOREIGN KEY (COMPANYID) REFERENCES COMPANY(COMPANYID) ENABLE,
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID) ENABLE
);

ALTER TABLE TAX
ADD FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEE(EMPLOYEEID);

ALTER TABLE HELPDESK
ADD FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEE(EMPLOYEEID);

COMMIT;



